In [1]:
import numpy as np
import matplotlib.pyplot as plt
import operator

In [3]:
group = np.array([[1.0, 1.1], [1.0, 1.0], [0, 0], [0, 0.1]])
labels = ['A', 'A', 'B', 'B']

In [4]:
size = group.shape[0]
size

4

In [10]:
group.shape

(4, 2)

In [12]:
(size,1)

(4, 1)

In [13]:
print(np.tile([0,0],(size,1)))

[[0 0]
 [0 0]
 [0 0]
 [0 0]]


In [9]:
diffmat = np.tile([0,0],(size,1)) - group
diffmat

array([[-1. , -1.1],
       [-1. , -1. ],
       [ 0. ,  0. ],
       [ 0. , -0.1]])

In [14]:
print(diffmat**2)

[[1.   1.21]
 [1.   1.  ]
 [0.   0.  ]
 [0.   0.01]]
